name: CI

on: [push]

jobs:
  cancel_previous_run:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.0
        with:
          access_token: ${{ github.token }}

  build:
    runs-on: ${{ matrix.os }}
    needs: cancel_previous_run
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Setup OCaml
      uses: ocaml/setup-ocaml@v2
    - name: Pin locally
      run: opam pin -y add --no-action .
    - name: Update packages and install locally
      run: opam install -y ffmpeg
    - name: Run tests locally
      run: eval $(opam env) && dune runtest
