name: CI

on: [push]

jobs:
  cancel_previous_run:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.0
        with:
          access_token: ${{ github.token }}

  build:
    runs-on: ${{ matrix.os }}
    needs: cancel_previous_run
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - name: Checkout latest code
      uses: actions/checkout@v1
    - name: Setup OCaml
      uses: ocaml/setup-ocaml@v2
    - name: Update packages
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
    - name: Pin locally
      run: opam pin -y add --no-action .
    - name: Install locally
      run: opam install -y ffmpeg
    - name: Run tests locally
      run: opam exec dune runtest
